version: '2'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_CONFIGURATION=Production
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py collectstatic --no-input &&
               gunicorn scigym.wsgi -b 0.0.0.0:8000 -w 3"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env